language: node_js
node_js:
- '0.10'
sudo: false
before_install: npm install -g grunt-cli
before_script: grunt build --verbose
deploy:
  provider: releases
  api_key:
    secure: PbeHwM34muUp/D+g9gbpBj/ABYtKRmPkgRpvSMl8zxFw/slFEoepA25komkh4QO1VGV5xGtUiIz8F6Rg+uhgWiid0F+GAxDjVc9NAUAeK9ONzKpo9H5f7JJrESBnEp06R6CVR/hVPN5v2UlKUJd2MoRYHKTM/GlnCY8/L+0j0bU=
  file: dist/cmv-widgets.zip
  on:
    repo: tmcgee/cmv-widgets
    tags: true
    all_branches: true
  skip_cleanup: true
notifications:
  slack:
    secure: NNR7OOLQ/aAwIhDqDgMgn5LSkQG98nQwKy72jHCUHZrJIsVP//tkzde7X4nvBs8Lbo+Or0kYoACqWmyB7OU8i1DrtAnDtCt4biJvUxub/ZKEeBwGXMRdXAhrzEHnf+j$
